// src/lib/amenitiesIcons.ts
export const amenitiesIcons = {
  "Accessible-height toilet": "pi.PiToilet",
  "Disabled parking spot": "pi.PiToilet",
  "Grab-rails for shower and toilet": "md.MdDragHandle",
  "Grab-rails in toilet": "md.MdDragHandle",
  "Path to entrance lit at night": "md.MdWbTwilight",
  "Shower bench": "pi.PiChairLight",
  "Shower chair": "pi.PiChairLight",
  "Single level home": "lia.LiaLevelUpAltSolid",
  "Step-free access": "io5.IoFootstepsOutline",
  "Tub with shower bench": "pi.PiChairLight",
  "Wheelchair accessible": "pi.PiWheelchair",
  "Wide clearance to bed": "io5.IoBedOutline",
  "Wide clearance to shower and toilet": "tb.TbViewportWide",
  "Wide doorway": "tb.TbViewportWide",
  "Wide hallway clearance": "tb.TbViewportWide",
  "Body soap": "fa.FaSoap",
  "Cleaning products": "gi.GiSoapExperiment",
  "Conditioner": "pi.PiHandSoapBold",
  "Hot water": "io5.IoWaterOutline",
  "Shampoo": "pi.PiHandSoapBold",
  "Shower gel": "pi.PiHandSoapBold",
  "Towels provided": "md.MdOutlineDryCleaning",
  "Clothing storage": "bi.BiCloset",
  "Coin Laundry": "md.MdOutlineLocalLaundryService",
  "Dryer in common space": "md.MdOutlineLocalLaundryService",
  "Mosquito net": "md.MdOutlineTexture",
  "Washer in common space": "md.MdOutlineLocalLaundryService",
  "Dvd player": "io5.IoTvOutline",
  "Foosball table": "io.IoIosFootball",
  "Game room": "pi.PiGameController",
  "Piano": "vsc.VscPiano",
  "Ping pong table": "pi.PiPingPongLight",
  "Pool table": "gi.GiPoolTableCorner",
  "Sound system": "gi.GiSoundWaves",
  "Baby bath": "pi.PiBaby",
  "Baby monitor": "pi.PiBaby",
  "Babysitter recommendations": "pi.PiBaby",
  "Bathtub": "pi.PiBathtub",
  "Board games": "fa.FaChessBoard",
  "Changing table": "md.MdOutlineBabyChangingStation",
  "Children’s books and toys": "io5.IoBookOutline",
  "Children’s dinnerware": "fa6.FaChildReaching",
  "Crib": "md.MdOutlineCrib",
  "Family/kid friendly": "fa6.FaChildReaching",
  "Fireplace guards": "gi.GiFireplace",
  "Game console": "gi.GiConsoleController",
  "High chair": "tb.TbChairDirector",
  "Outlet covers": "tb.TbOutlet",
  "Pack ’n Play/travel crib": "md.MdOutlineCrib",
  "Room-darkening shades": "md.MdOutlineRollerShadesClosed",
  "Stair gates": "ai.AiOutlineGateway",
  "Table corner guards": "md.MdRoundedCorner",
  "Window guards": "md.MdRoundedCorner",
  "Portable fans": "pi.PiFanLight",
  "Carbon monoxide detector": "md.MdAddAlarm",
  "Emergency exit": "io.IoMdExit",
  "Fire extinguisher": "pi.PiFireExtinguisher",
  "First aid kit": "bi.BiFirstAid",
  "Smoke detector": "md.MdAddAlarm",
  "Baking sheet": "md.MdOutlineBakeryDining",
  "Barbeque utensils": "lu.LuUtensils",
  "Blender": "md.MdOutlineBlender",
  "Breakfast": "md.MdOutlineFreeBreakfast",
  "Coffee": "lu.LuCoffee",
  "Coffee maker": "md.MdOutlineCoffeeMaker",
  "Cookware": "pi.PiCookingPot",
  "Dining table": "pi.PiPicnicTableLight",
  "Dishes and silverware": "lia.LiaUtensilsSolid",
  "Dishwasher": "bi.BiSolidWasher",
  "Freezer": "tb.TbFreezeRowColumn",
  "Ice maker": "ci.CiVoicemail",
  "Kettle": "gi.GiCoffeePot",
  "Microwave": "lu.LuMicrowave",
  "Mini fridge": "bi.BiFridge",
  "Oven": "pi.PiOven",
  "Refrigerator": "ri.RiFridgeLine",
  "Rice maker": "fa6.FaBowlRice",
  "Stove": "pi.PiOven",
  "Toaster": "gr.GrToast",
  "Trash compactor": "fa.FaRegTrashAlt",
  "Wine glasses": "pi.PiWineDuotone",
  "Beach": "fa6.FaUmbrellaBeach",
  "Beach Front": "fa6.FaUmbrellaBeach",
  "Beach View": "fa.FaWater",
  "Beach access": "fa6.FaUmbrellaBeach",
  "City View": "gi.GiModernCity",
  "Desert View": "md.MdLandscape",
  "Downtown": "md.MdLocationCity",
  "Garden View": "bs.BsFlower1",
  "Golf course front": "io5.IoGolfOutline",
  "Golf view": "io5.IoGolfOutline",
  "Lake": "fa6.FaWater",
  "Lake Front": "fa6.FaWater",
  "Lake access": "fa6.FaWater",
  "Laundromat nearby": "md.MdOutlineLocalLaundryService",
  "Mountain": "md.MdOutlineLandscape",
  "Mountain view": "md.MdOutlineLandscape",
  "Near Ocean": "bs.BsWater",
  "Ocean Front": "bs.BsWater",
  "Resort": "lu.LuBuilding2",
  "Resort access": "lu.LuBuilding2",
  "Rural": "md.MdOutlineLandscape",
  "Sea view": "bs.BsWater",
  "Ski In": "fa.FaSkiing",
  "Ski Out": "fa.FaSkiing",
  "Ski in/Ski out": "fa.FaSkiing",
  "Town": "pi.PiCity",
  "Village": "md.MdOutlineHolidayVillage",
  "Water View": "bs.BsWater",
  "Waterfront": "bs.BsWater",
  "Cleaning Disinfection": "md.MdOutlineCleaningServices",
  "Cleaning before checkout": "md.MdOutlineCleaningServices",
  "Desk": "ci.CiDesktopMouse1",
  "Enhanced cleaning practices": "io5.IoSparklesOutline",
  "High touch surfaces disinfected": "io5.IoSparklesOutline",
  "Laptop friendly workspace": "ci.CiDesktopMouse1",
  "Long term stays allowed": "lu.LuClock6",
  "Luggage dropoff allowed": "md.MdOutlineLuggage",
  "Casinos": "bs.BsCoin",
  "Cycling": "md.MdOutlineDirectionsBike",
  "Fishing": "gi.GiBoatFishing",
  "Golf - Optional": "io5.IoGolfOutline",
  "Horseback Riding": "fa.FaHorseHead",
  "Mountain Climbing": "cg.CgCodeClimate",
  "Museums": "md.MdOutlineMuseum",
  "Rock Climbing": "cg.CgCodeClimate",
  "Shopping": "ci.CiShoppingCart",
  "Theme Parks": "md.MdOutlinePark",
  "Water Parks": "tb.TbWaterpolo",
  "Water Sports": "tb.TbWaterpolo",
  "Zoo": "md.MdOutlinePets",
  "BBQ grill": "md.MdOutlineOutdoorGrill",
  "Beach essentials": "md.MdOutlineBeachAccess",
  "Bicycles available": "md.MdDirectionsBike",
  "Bikes": "md.MdDirectionsBike",
  "Boat slip": "io5.IoBoatOutline",
  "Doorman": "io5.IoMan",
  "Fire Pit": "fa6.FaFireFlameCurved",
  "Garden or backyard": "gi.GiGrass",
  "Hammock": "md.MdOutlineAirlineSeatReclineExtra",
  "Kayak": "md.MdKayaking",
  "Outdoor kitchen": "md.MdOutlineOutdoorGrill",
  "Outdoor seating (furniture)": "pi.PiPicnicTable",
  "River": "fa.FaWater",
  "Free parking on premises": "ci.CiParking1",
  "Free parking on street": "ci.CiParking1",
  "Garage": "ci.CiParking1",
  "Paid parking": "ci.CiParking1",
  "Paid parking off premises": "ci.CiParking1",
  "Communal pool": "md.MdOutlinePool",
  "Indoor pool": "md.MdOutlinePool",
  "Outdoor pool": "md.MdOutlinePool",
  "Private pool": "md.MdOutlinePool",
  "Rooftop pool": "md.MdOutlinePool",
  "Swimming pool": "md.MdOutlinePool",
  "Air conditioning": "io5.IoSnowOutline",
  "Bed linens": "io5.IoBedOutline",
  "Cable TV": "bs.BsTv",
  "Dryer": "bi.BiSolidDryer",
  "Elevator": "pi.PiElevator",
  "Essentials": "ci.CiStar",
  "Hair dryer": "pi.PiHairDryerLight",
  "Hangers": "bi.BiCloset",
  "Heating": "fa6.FaHotjar",
  "Indoor fireplace": "md.MdOutlineFireplace",
  "Internet": "io5.IoWifiSharp",
  "Kitchen": "gi.GiKitchenTap",
  "Patio or balcony": "md.MdOutlineDeck",
  "TV": "bs.BsTv",
  "Washer": "bi.BiSolidWasher",
  "Wireless Internet": "io5.IoWifiSharp",
  "Ceiling fan": "pi.PiFan",
  "EV charger": "bs.BsLightningCharge",
  "Extra pillows and blankets": "gi.GiPillow",
  "Pocket Wifi": "io5.IoWifiSharp",
  "Private entrance": "md.MdOutlineSensorDoor",
  "Safe": "ri.RiSafeLine",
  "Stereo system": "gi.GiSoundWaves",
  "Gym": "cg.CgGym",
  "Hot tub": "lia.LiaHotTubSolid",
  "Sauna": "md.MdWorkspacesOutline",
  "Spa": "md.MdWorkspacesOutline",
  "Pets allowed": "md.MdOutlinePets",
  "Suitable for children (2-12 years)": "bi.BiChild",
  "Suitable for infants (under 2 years)": "bi.BiChild"
};