[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.4"
  NODE_ENV = "NODE_ENV=development pnpm install && NODE_ENV=production pnpm run build"
  NPM_FLAGS = "--frozen-lockfile"

[context.production.environment]
  VITE_API_TOKEN = "your_token_here"

[functions]
  directory = "netlify/functions"

[[scheduled_functions]]
  name = "refreshToken"
  schedule = "0 */23 * * *"  # Updates the schedule to every 23 hours

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = true

[build.cache]
  # Clear the cache for node_modules
  paths = ["node_modules/**"]