[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[scheduled_functions]]
  name = "refreshToken"
  schedule = "0 */12 * * *"

[[scheduled_functions]]
  name = "cache-listings"
  schedule = "0 */12 * * *"

[build.processing]
  skip_processing = true

[build.cache]
  # Clear the cache for node_modules
  paths = ["node_modules/**"]