[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.14.1"
  NODE_ENV = "production"
  NPM_FLAGS = "--frozen-lockfile"

[context.production.environment]
  VITE_API_TOKEN = "your_token_here"

[functions]
  directory = "netlify/functions"

[[scheduled_functions]]
  name = "refreshToken"
  schedule = "0 */23 * * *"  # Update the schedule to every 23 hours

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-cache-clear"