[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled_functions]]
  path = "refreshToken"
  schedule = "@daily"

[[scheduled_functions]]
  path = "cache-listings"
  schedule = "@daily"

[build.processing]
  skip_processing = true

[build.cache]
  # Clear the cache for node_modules
  paths = ["node_modules/**"]