[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18.17.1"  # Ensure this is a valid Node.js version

[functions."refreshToken"]
  schedule = "@daily"

[functions."cache-images"]
  schedule = "@daily"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = ["dist/**/*"]  # Cache all generated pages

[build.processing]
  skip_processing = true

[build.cache]
  paths = ["node_modules/**"]