[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18.17.1"  # Update to a valid Node.js version

[[scheduled_functions]]
  path = "refreshToken"
  schedule = "@daily"

[[scheduled_functions]]
  path = "cache-listings"
  schedule = "@daily"

[build.processing]
  skip_processing = true

[build.cache]
  paths = ["node_modules/**"]