name: deploy to firebase functions

on:
    push:
          branches:
              - main

jobs:
    build-and-deploy
        runs-on: vercel

        steps:
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: set up node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install Dependencies
          run: npm install

        - name: Install Firebase CLI
          run: npm install -g firebase-tools

        - name: Build
          env:
            FIREBASE_PRIVATE_KEY_ID: ${{ vars.FIREBASE_PRIVATE_KEY_ID }}
            FIREBASE_PRIVATE_KEY: ${{ vars.FIREBASE_PRIVATE_KEY }}
            FIREBASE_CLIENT_EMAIL: ${{ vars.FIREBASE_CLIENT_EMAIL} }
            FIREBASE_CLIENT_ID: ${{ vars.FIREBASE_CLIENT_ID }}
            FIREBASE_AUTH_URI: ${{ vars.FIREBASE_AUTH_URI }
            FIREBASE_TOKEN_URI: ${{ vars.FIREBASE_TOKEN_URI }
            FIREBASE_AUTH_CERT_URL: ${{ vars.FIREBASE_AUTH_CERT_URL }}
            FIREBASE_CLIENT_CERT_URL: ${{ vars.FIREBASE_CLIENT_CERT_URL }}
          run: CI=false pnpm run build

        - name: Deploy to Hosting and Fuctions
          run: firebase deploy --only hosting,functions --token ${{ secrets.
          FIREBASE_TOKEN_URI }} --project dev --force