name: Generate Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.1'

      - name: Install dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get install -y jq
        shell: bash

      - name: Generate Bearer Token
        id: generate-token
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          RESPONSE=$(curl --location --request POST 'https://open-api.guesty.com/oauth2/token' \
            --header 'accept: application/json' \
            --data-urlencode 'grant_type=client_credentials' \
            --data-urlencode 'scope=open-api' \
            --data-urlencode "client_secret=${CLIENT_SECRET}" \
            --data-urlencode "client_id=${CLIENT_ID}")

          echo "Response: $RESPONSE"

          # Extract the bearer token from the response
          BEARER_TOKEN=$(echo $RESPONSE | jq -r '.access_token')

          echo "Generated Bearer Token: $BEARER_TOKEN"

          # Save the bearer token to a file
          echo $BEARER_TOKEN > bearer_token.txt
        shell: bash

      - name: Upload Bearer Token Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bearer-token
          path: bearer_token.txt