name: Generate Bearer Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install pnpm
      run: |
        npm install -g pnpm
        pnpm setup
      env:
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Verify pnpm Installation
      run: pnpm --version
      env:
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Install Dependencies
      run: pnpm install
      env:
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Install jq
      run: sudo apt-get install -y jq
      env:
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Generate Bearer Token
      id: generate-token
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SHELL: /bin/bash
      run: |
        RESPONSE=$(curl --location --request POST 'https://open-api.guesty.com/oauth2/token' \
          --header 'accept: application/json' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'scope=open-api' \
          --data-urlencode "client_secret=${CLIENT_SECRET}" \
          --data-urlencode "client_id=${CLIENT_ID}")

        echo "Response: $RESPONSE"

        # Extract the bearer token from the response
        BEARER_TOKEN=$(echo $RESPONSE | jq -r '.access_token')

        echo "Generated Bearer Token: $BEARER_TOKEN"

        # Set the bearer token as an environment variable
        echo "BEARER_TOKEN=${BEARER_TOKEN}" >> $GITHUB_ENV
      shell: bash

    - name: Log Bearer Token
      run: echo ${{ env.BEARER_TOKEN }}
      env:
        BEARER_TOKEN: ${{ env.BEARER_TOKEN }}
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Use Bearer Token in Astro Project
      run: |
        # Ensure the .env file exists
        touch .env
        # Append the bearer token to the .env file
        echo "VITE_API_TOKEN=${{ env.BEARER_TOKEN }}" >> .env
        # Log the .env file content for debugging purposes
        cat .env
      env:
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable

    - name: Install Dependencies and Build Project
      run: |
        # Install dependencies
        pnpm install
        # Build the Astro project
        pnpm build
        # Deploy or perform any other necessary tasks
        # e.g., pnpm deploy
      env:
        BEARER_TOKEN: ${{ env.BEARER_TOKEN }}
        VITE_API_TOKEN: ${{ env.BEARER_TOKEN }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
        CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        SHELL: /bin/bash  # Explicitly set the SHELL environment variable