name: Generate Bearer Token

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 */23 * * *' # Runs every 23 hours

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install pnpm
      run: |
        npm install -g pnpm
        pnpm setup
      shell: bash

    - name: Verify pnpm Installation
      run: pnpm --version
      shell: bash

    - name: Install Dependencies
      run: pnpm install
      shell: bash

    - name: Install jq
      run: sudo apt-get install -y jq
      shell: bash

    - name: Generate Bearer Token
      id: generate-token
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        RESPONSE=$(curl --location --request POST 'https://open-api.guesty.com/oauth2/token' \
          --header 'accept: application/json' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'scope=open-api' \
          --data-urlencode "client_secret=${CLIENT_SECRET}" \
          --data-urlencode "client_id=${CLIENT_ID}")

        echo "Response: $RESPONSE"

        # Extract the bearer token from the response
        BEARER_TOKEN=$(echo $RESPONSE | jq -r '.access_token')

        echo "Generated Bearer Token: $BEARER_TOKEN"

        # Set the bearer token as an environment variable
        echo "BEARER_TOKEN=${BEARER_TOKEN}" >> $GITHUB_ENV
      shell: bash

    - name: Log Bearer Token
      run: echo ${{ env.BEARER_TOKEN }}
      shell: bash

    - name: Use Bearer Token in Astro Project
      run: |
        # Ensure the .env.local file exists
        touch .env.local
        # Append the bearer token to the .env.local file
        echo "VITE_API_TOKEN=${{ env.BEARER_TOKEN }}" >> .env.local
        # Log the .env.local file content for debugging purposes
        cat .env.local
      shell: bash

    - name: Install Dependencies and Build Project
      run: |
        # Install dependencies
        pnpm install
        # Build the Astro project
        pnpm build
        # Deploy or perform any other necessary tasks
        # e.g., pnpm deploy
      env:
        VITE_API_TOKEN: ${{ env.BEARER_TOKEN }}
      shell: bash