name: Get Token

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash  # Set SHELL environment variable globally

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup

      - name: Verify pnpm Installation
        run: pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Print Shell
        run: echo $SHELL

      - name: Navigate and Run Setup Script
        run: |
          cd path/to/your/directory
          ./scripts/setup.sh

      - name: Use Bearer Token in Astro Project
        run: |
          # Ensure the .env file exists
          touch .env.development
          # Append the bearer token to the .env file
          echo "VITE_API_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env.development
          # Log the .env.development file content for debugging purposes
          cat .env.development
