name: USE THIS ONE Retrieve Bearer Token

on:
  workflow_dispatch:

jobs:
  retrieve-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Use stored Bearer Token
        run: |
          # Ensure the .env.local file exists
          touch .env.local
          # Append the stored bearer token to the .env.local file
          echo "VITE_API_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env.local

      - name: Verify .env.local file
        run: cat .env.local