name: Import Bearer Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate token
        run: node generateToken.js

      - name: Save token to .env
        run: echo "BEARER_TOKEN=${{ steps.generate-token.outputs.token }}" > .env

      - name: Upload .env artifact
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env