name: Get Token

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          # Ensure the .env file exists
          touch .env.development
          # Append the bearer token to the .env file
          echo "VITE_API_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env.development
          # Log the .env.development file content for debugging purposes
          cat .env.development
        env:
          SHELL: /bin/bash

      - name: Verify Token
        run: |
          # Simple script to verify that the token is correctly set
          echo "Bearer Token is set in .env file"
        env:
          SHELL: /bin/bash
