name: Retrieve Bearer Token

on:
  push:
    branches:
      - main

jobs:
  retrieve-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Retrieve Bearer Token
        run: echo "VITE_API_TOKEN=${{ secrets.BEARER_TOKEN }}" > .env

      - name: Install dependencies
        run: pnpm install

      - name: Run your script
        run: node refreshToken.js