name: Retrieve Bearer Token

on:
  workflow_dispatch:

jobs:
  retrieve-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run refreshToken script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: node refreshToken.js

      - name: Create .env.local file
        run: cp .env .env.local

      - name: Verify .env.local file
        run: cat .env.local